"""updated models

Revision ID: 4c7eb176e40a
Revises: a23e15d0d8f9
Create Date: 2025-11-02 16:32:44.604370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c7eb176e40a'
down_revision: Union[str, Sequence[str], None] = 'a23e15d0d8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('medicine_tags')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('file_assets')
    op.drop_table('issues')
    op.drop_table('alternatives')
    op.drop_table('carts')
    op.drop_table('role_permissions')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_permissions_permission_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('medicine_side_effects')
    op.drop_table('discounts')
    op.drop_table('payments')
    op.drop_index(op.f('ix_medicines_generic_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_medicine_name'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_table('issue_attachments')
    op.drop_table('address_type')
    op.drop_index(op.f('ix_password_reset_id'), table_name='password_reset')
    op.drop_table('password_reset')
    op.drop_table('prescription_items')
    op.drop_table('discount_parameters')
    op.drop_table('user_roles')
    op.drop_table('gst_slabs')
    op.drop_table('cart_items')
    op.drop_table('medicine_images')
    op.drop_table('discount_medicines')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_side_effects_side_effect'), table_name='side_effects')
    op.drop_table('side_effects')
    op.drop_table('coupons')
    op.drop_table('issue_messages')
    op.drop_table('customer_profile')
    op.drop_table('discount_types')
    op.drop_table('prescriptions')
    op.drop_table('invoice_items')
    op.drop_table('reviews')
    op.drop_table('orders')
    op.drop_table('medicine_categories')
    op.drop_table('revoked_tokens')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_categories_category_name'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('medicine_batches')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('medicine_alternatives')
    op.drop_table('issue_categories')
    op.drop_table('discount_categories')
    op.drop_table('management_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_profile',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('profile_pic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_pic'], ['file_assets.asset_id'], name=op.f('management_profile_profile_pic_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('management_profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('management_profile_pkey'))
    )
    op.create_table('discount_categories',
    sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('discount_categories_category_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('discount_categories_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.discount_id'], name=op.f('discount_categories_discount_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('discount_id', 'category_id', name=op.f('discount_categories_pkey'))
    )
    op.create_table('issue_categories',
    sa.Column('category_id', sa.INTEGER(), server_default=sa.text("nextval('issue_categories_category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='issue_categories_deleted_by_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', name='issue_categories_pkey'),
    sa.UniqueConstraint('name', name='issue_categories_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('medicine_alternatives',
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alternative_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alternative_id'], ['alternatives.alternative_id'], name=op.f('medicine_alternatives_alternative_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('medicine_alternatives_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('medicine_alternatives_medicine_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('medicine_id', 'alternative_id', name=op.f('medicine_alternatives_pkey'))
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.INTEGER(), server_default=sa.text("nextval('tags_tag_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='tags_deleted_by_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', name='tags_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.INTEGER(), server_default=sa.text("nextval('invoices_invoice_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('issue_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('invoice_pdf_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtotal_amount', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('total_tax', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('gross_amount', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('payment_status', postgresql.ENUM('unpaid', 'paid', name='invoice_payment_status_enum'), server_default=sa.text("'unpaid'::invoice_payment_status_enum"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_pdf_id'], ['file_assets.asset_id'], name='invoices_invoice_pdf_id_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='invoices_order_id_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='invoices_user_id_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id', name='invoices_pkey'),
    sa.UniqueConstraint('invoice_number', name='invoices_invoice_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('medicine_batches',
    sa.Column('batch_id', sa.INTEGER(), server_default=sa.text("nextval('medicine_batches_batch_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('selling_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='medicine_batches_deleted_by_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name='medicine_batches_medicine_id_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', name='medicine_batches_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('categories',
    sa.Column('category_id', sa.INTEGER(), server_default=sa.text("nextval('categories_category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='categories_deleted_by_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', name='categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_categories_category_name'), 'categories', ['category_name'], unique=True)
    op.create_table('sessions',
    sa.Column('session_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('device_info', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('sessions_pkey'))
    )
    op.create_table('revoked_tokens',
    sa.Column('revoked_token_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('revoked_token_id', name=op.f('revoked_tokens_pkey'))
    )
    op.create_table('medicine_categories',
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('medicine_categories_category_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('medicine_categories_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('medicine_categories_medicine_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('medicine_id', 'category_id', name=op.f('medicine_categories_pkey'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.INTEGER(), server_default=sa.text("nextval('orders_order_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'shipped', 'delivered', 'canceled', 'returned', name='order_status_enum'), server_default=sa.text("'pending'::order_status_enum"), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], name='orders_customer_id_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='orders_deleted_by_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.member_id'], name='orders_member_id_fkey'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.prescription_id'], name='orders_prescription_id_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', name='orders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('visible', 'hidden', 'flagged', 'deleted', name='review_status'), server_default=sa.text("'visible'::review_status"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], name=op.f('reviews_customer_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('reviews_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('reviews_medicine_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', name=op.f('reviews_pkey'))
    )
    op.create_table('invoice_items',
    sa.Column('invoice_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('gst_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('cgst', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('sgst', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('igst', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], name=op.f('invoice_items_invoice_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('invoice_items_medicine_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_item_id', name=op.f('invoice_items_pkey'))
    )
    op.create_table('prescriptions',
    sa.Column('prescription_id', sa.INTEGER(), server_default=sa.text("nextval('prescriptions_prescription_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'verified', 'rejected', name='prescription_status_enum'), server_default=sa.text("'pending'::prescription_status_enum"), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['file_assets.asset_id'], name='prescriptions_asset_id_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], name='prescriptions_customer_id_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='prescriptions_deleted_by_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], name='prescriptions_verified_by_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('prescription_id', name='prescriptions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('discount_types',
    sa.Column('discount_type_id', sa.INTEGER(), server_default=sa.text("nextval('discount_types_discount_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='discount_types_deleted_by_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('discount_type_id', name='discount_types_pkey'),
    sa.UniqueConstraint('type_name', name='discount_types_type_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('customer_profile',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_pic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.address_id'], name=op.f('customer_profile_address_id_fkey')),
    sa.ForeignKeyConstraint(['profile_pic'], ['file_assets.asset_id'], name=op.f('customer_profile_profile_pic_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('customer_profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('customer_profile_pkey'))
    )
    op.create_table('issue_messages',
    sa.Column('message_id', sa.INTEGER(), server_default=sa.text("nextval('issue_messages_message_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='issue_messages_deleted_by_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], name='issue_messages_issue_id_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name='issue_messages_sender_id_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name='issue_messages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('coupons',
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('valid_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('coupons_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.discount_id'], name=op.f('coupons_discount_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', name=op.f('coupons_pkey')),
    sa.UniqueConstraint('code', name=op.f('coupons_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('side_effects',
    sa.Column('side_effect_id', sa.INTEGER(), server_default=sa.text("nextval('side_effects_side_effect_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('side_effect', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='side_effects_deleted_by_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('side_effect_id', name='side_effects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_side_effects_side_effect'), 'side_effects', ['side_effect'], unique=True)
    op.create_table('addresses',
    sa.Column('address_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('house_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('street_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('locality', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pincode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['address_type.type_id'], name=op.f('addresses_type_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('addresses_user_id_fkey')),
    sa.PrimaryKeyConstraint('address_id', name=op.f('addresses_pkey'))
    )
    op.create_table('discount_medicines',
    sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('discount_medicines_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.discount_id'], name=op.f('discount_medicines_discount_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('discount_medicines_medicine_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('discount_id', 'medicine_id', name=op.f('discount_medicines_pkey'))
    )
    op.create_table('medicine_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_assets.asset_id'], name=op.f('medicine_images_file_asset_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('medicine_images_medicine_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('medicine_images_pkey'))
    )
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.cart_id'], name=op.f('cart_items_cart_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('cart_items_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('cart_items_medicine_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('cart_item_id', name=op.f('cart_items_pkey'))
    )
    op.create_table('gst_slabs',
    sa.Column('hsn_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gst_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='gst_slabs_deleted_by_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('hsn_code', name='gst_slabs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('user_roles_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('user_roles_pkey'))
    )
    op.create_table('discount_parameters',
    sa.Column('parameter_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('param_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('param_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('discount_parameters_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.discount_id'], name=op.f('discount_parameters_discount_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('parameter_id', name=op.f('discount_parameters_pkey'))
    )
    op.create_table('prescription_items',
    sa.Column('pi_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('prescription_items_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('prescription_items_medicine_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.prescription_id'], name=op.f('prescription_items_prescription_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('pi_id', name=op.f('prescription_items_pkey'))
    )
    op.create_table('password_reset',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('password_reset_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_pkey')),
    sa.UniqueConstraint('token', name=op.f('password_reset_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_password_reset_id'), 'password_reset', ['id'], unique=False)
    op.create_table('address_type',
    sa.Column('type_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('type_id', name=op.f('address_type_pkey')),
    sa.UniqueConstraint('name', name=op.f('address_type_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('issue_attachments',
    sa.Column('attachment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('issue_attachments_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['issue_messages.message_id'], name=op.f('issue_attachments_message_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id', name=op.f('issue_attachments_pkey'))
    )
    op.create_table('medicines',
    sa.Column('medicine_id', sa.INTEGER(), server_default=sa.text("nextval('medicines_medicine_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('medicine_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('generic_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_prescribed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=False),
    sa.Column('hsn_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('image_asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name='medicines_deleted_by_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['hsn_code'], ['gst_slabs.hsn_code'], name='medicines_hsn_code_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['image_asset_id'], ['file_assets.asset_id'], name='medicines_image_asset_id_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('medicine_id', name='medicines_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_medicines_medicine_name'), 'medicines', ['medicine_name'], unique=False)
    op.create_index(op.f('ix_medicines_generic_name'), 'medicines', ['generic_name'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', 'refunded', name='payment_status_enum'), server_default=sa.text("'pending'::payment_status_enum"), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('payments_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('payments_order_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('payments_pkey'))
    )
    op.create_table('discounts',
    sa.Column('discount_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discount_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('min_purchase_amount', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=True),
    sa.Column('max_discount_amount', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=True),
    sa.Column('usage_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('discounts_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['discount_type_id'], ['discount_types.discount_type_id'], name=op.f('discounts_discount_type_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('discount_id', name=op.f('discounts_pkey'))
    )
    op.create_table('medicine_side_effects',
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('side_effect_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('medicine_side_effects_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('medicine_side_effects_medicine_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['side_effect_id'], ['side_effects.side_effect_id'], name=op.f('medicine_side_effects_side_effect_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('medicine_id', 'side_effect_id', name=op.f('medicine_side_effects_pkey'))
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.INTEGER(), server_default=sa.text("nextval('permissions_permission_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('permission_id', name='permissions_pkey'),
    sa.UniqueConstraint('name', name='permissions_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_permissions_permission_id'), 'permissions', ['permission_id'], unique=False)
    op.create_table('family_members',
    sa.Column('member_id', sa.INTEGER(), server_default=sa.text("nextval('family_members_member_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='family_members_user_id_fkey'),
    sa.PrimaryKeyConstraint('member_id', name='family_members_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], name=op.f('role_permissions_permission_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('role_permissions_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('carts',
    sa.Column('cart_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], name=op.f('carts_customer_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('carts_deleted_by_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', name=op.f('carts_pkey'))
    )
    op.create_table('alternatives',
    sa.Column('alternative_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('alternatives_deleted_by_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('alternative_id', name=op.f('alternatives_pkey')),
    sa.UniqueConstraint('name', name=op.f('alternatives_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('issues',
    sa.Column('issue_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'in_progress', 'resolved', 'closed', name='issue_status_enum'), server_default=sa.text("'open'::issue_status_enum"), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], name=op.f('issues_assigned_to_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['issue_categories.category_id'], name=op.f('issues_category_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], name=op.f('issues_customer_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('issues_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('issues_order_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', name=op.f('issues_pkey'))
    )
    op.create_table('file_assets',
    sa.Column('asset_id', sa.INTEGER(), server_default=sa.text("nextval('file_assets_asset_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name='file_assets_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('asset_id', name='file_assets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('roles',
    sa.Column('role_id', sa.INTEGER(), server_default=sa.text("nextval('roles_role_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.batch_id'], name=op.f('order_items_batch_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('order_items_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('order_items_order_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id', name=op.f('order_items_pkey'))
    )
    op.create_table('medicine_tags',
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], name=op.f('medicine_tags_deleted_by_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('medicine_tags_medicine_id_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], name=op.f('medicine_tags_tag_id_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('medicine_id', 'tag_id', name=op.f('medicine_tags_pkey'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('users_role_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone_number', name=op.f('users_phone_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###
